id: 8a3636bdbfda42f09b254b82aa39201d
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_100-The_Ornament_of_the_Light_of_Awareness-v1
  language: en
  author: ''
  volume: {}
